from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware

# If you want to use ElevenLabs later, uncomment this and wire it up:
# from sst_service_local import speech_to_text

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    return {"message": "Backend is up :)"}


@app.post("/sst")
async def sst(file: UploadFile = File(...)):
    """
    Accepts an uploaded audio file from the frontend and returns
    a transcript + a dummy explanation so the UI can light up.
    """
    audio_bytes = await file.read()
    print(f"Got audio bytes: {len(audio_bytes)}")

    # --- SIMPLE TEST VERSION (no ElevenLabs yet) ---
    transcript = "This is a test transcript from your Convers8 backend."
    answer = (
        "This is a sample explanation generated by the AI tutor "
        "based on what you just said."
    )

    # If you want to call ElevenLabs later, you'd do something like:
    # try:
    #     transcript = speech_to_text(audio_bytes, env_like_object)
    # except Exception as e:
    #     print("Error in speech_to_text:", e)
    #     transcript = "There was an error calling the speech-to-text service."

    return {"transcript": transcript, "answer": answer}
